### ISSUE TITLE
setup.py records the full python path

### ISSUE THREAD

**Issue by fxcoudert** [sloria/doitlive#161] opened 2019-12-30 20:53 UTC
In Homebrew we install `doitlive` with:

```
python3 setup.py install --prefix=/usr/local/Cellar/doitlive/4.3.0_5/libexec
```

where `python3` in `PATH` is `/usr/local/bin/python3`, which is a symlink to `/usr/local/Cellar/python/3.7.6/bin/python3`. However, when we do this, the `doitlive` in `/usr/local/Cellar/doitlive/4.3.0_5/libexec/bin` contains this as a shebang:

```
#!/usr/local/Cellar/python/3.7.6/bin/python3
```

which is not desirable at all for us. Other python packages don't do that, so I think it's an issue specific to doitlive. It would be nice if `setup.py` could simply use the python path that is given to it, rather than try to guess.

**Comment by sloria** [comment] 2020-01-02 14:58
I'm not sure I understand the problem here--there's no shebang in the current setup.py. Is Homebrew adding that? 🤔

**Comment by fxcoudert** [comment] 2020-01-02 16:10
The problematic shebang is not in `setup.py` but in the `dotitlive` script generated by `setup.py`

**Comment by sloria** [comment] 2020-01-02 16:28
Oh ok. But it seems the problem isn't specific to doitlive, right? We're not doing anything particularly special in setup.py that would differ significantly from other Python CLIs.

**Comment by sloria** [comment] 2024-01-31 11:18
Closing, since both the homebrew installation and pip installation have changed significantly (setup.py isn't even used any more)

**Closed** 2024-01-31 11:17 UTC
